LinkedNewsChatApp/Controllers/NewsEditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LinkedNewsChatApp.Data;
using LinkedNewsChatApp.Models;
using DataLayer;
using NuGet.Protocol.Core.Types;

namespace LinkedNewsChatApp.Controllers
{
    public class NewsEditController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly NewsRepository _repository;
        public NewsEditController(ApplicationDbContext context, NewsRepository repository)
        {
            _context = context;  
            _repository = repository;
        }
        

        
        // GET: NewsEdit
       
        public async Task<IActionResult> Index(int page = 1)
        {
            int pageSize = 10;
            var news = _context.news.AsQueryable(); ;
         
            int totalNews = await news.CountAsync();
            int totalPages = (int)Math.Ceiling((decimal)totalNews / pageSize);


            if (page < 1)
            {
                page = 1;
            }
            else if (page > totalPages)
            {
                page = totalPages;
            }
            if (totalNews != 0)
            {
                var selectedNews = await news.Skip((page - 1) * pageSize)
                                             .Take(pageSize)
                                             .ToListAsync();
                ViewBag.TotalPages = totalPages;
                ViewBag.CurrentPage = page;
              
                return View(selectedNews);
            }
            else
            {

                return View("Empty");
            }
        }
        // GET: NewsEdit/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.news == null)
            {
                return NotFound();
            }

            var news = await _context.news
                .FirstOrDefaultAsync(m => m.id == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // GET: NewsEdit/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: NewsEdit/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,title,text,Category")] News news, IFormFile photo, string password)
        {
            if (password == "d5n!_4RX")
            {
                if (photo != null)
                {
                    string extension = Path.GetExtension(photo.FileName);
                    if (extension != null &&
                        (extension.ToLower() == ".jpg" ||
                         extension.ToLower() == ".jpeg" ||
                         extension.ToLower() == ".png"))
                    {

                    }
                    else
                    {
                        return BadRequest("Файл повинен бути у форматі jpg, jpeg або png");
                    }
                }


                byte[] photoByte;
                using (var ms = new MemoryStream())
                {
                    photo.CopyTo(ms);
                    byte[] fileBytes = ms.ToArray();
                    photoByte = fileBytes;
                }
                DateTime day = DateTime.Now;
                day = day.AddHours(10);
                var newsobj = new News() { id = news.id, title = news.title, text = news.text, photo = photoByte, Time = day, Category = news.Category };
                // if (ModelState.IsValid)
                // {
                _context.Add(newsobj);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
                //}
                //return View(news);
            }
            else
            {
                return View("Incorrect");
            }
        }

        // GET: NewsEdit/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.news == null)
            {
                return NotFound();
            }

            var news = await _context.news.FindAsync(id);
            if (news == null)
            {
                return NotFound();
            }
            return View(news);
        }

        // POST: NewsEdit/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,title,text,Category")] News news, IFormFile photo, string password)
        {
            if (password == "d5n!_4RX")
            {
                if (id != news.id)
                {
                    return NotFound();
                }



                if (photo != null)
                {
                    string extension = Path.GetExtension(photo.FileName);
                    if (extension != null &&
                        (extension.ToLower() == ".jpg" ||
                         extension.ToLower() == ".jpeg" ||
                         extension.ToLower() == ".png"))
                    {

                    }
                    else
                    {
                        return BadRequest("Файл повинен бути у форматі jpg, jpeg або png");
                    }



                    byte[] photoByte;
                    using (var ms = new MemoryStream())
                    {
                        photo.CopyTo(ms);
                        byte[] fileBytes = ms.ToArray();
                        photoByte = fileBytes;
                    }
                    DateTime day = DateTime.Now;
                    day = day.AddHours(10);
                    var newsobj = new News() { id = news.id, title = news.title, text = news.text, photo = photoByte, Time = day, Category = news.Category };



                    //if (ModelState.IsValid)
                    //{
                    try
                    {
                        _context.Update(newsobj);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!NewsExists(news.id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
                else
                {
                    var newsoperation = new NewsOperations.NewsOperations(_repository);
                    byte[] phot = _repository.GetNewsPhoto(news.id);
                    DateTime day = DateTime.Now;
                    day = day.AddHours(10);
                    var newsobj = new News() { id = news.id, title = news.title, text = news.text, photo = phot, Time = day, Category = news.Category };



                    //if (ModelState.IsValid)
                    //{
                    try
                    {
                        _context.Update(newsobj);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!NewsExists(news.id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
                return RedirectToAction(nameof(Index));
                // }
                //return View(news);
            }
            else
            {
                return View("Incorrect");
            }
        }

        // GET: NewsEdit/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            
                if (id == null || _context.news == null)
                {
                    return NotFound();
                }

                var news = await _context.news
                    .FirstOrDefaultAsync(m => m.id == id);
                if (news == null)
                {
                    return NotFound();
                }

                return View(news);
            
            
        }

        // POST: NewsEdit/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, string password)
        {
            if (password == "d5n!_4RX")
            {
                if (_context.news == null)
                {
                    return Problem("Entity set 'ApplicationDbContext.news'  is null.");
                }
                var news = await _context.news.FindAsync(id);
                if (news != null)
                {
                    _context.news.Remove(news);
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View("Incorrect");
            }
        }

        public async Task<IActionResult> DataView(int? id)
        {
            if (id == null || _context.news == null)
            {
                return NotFound();
            }

            var news = await _context.news
                .FirstOrDefaultAsync(m => m.id == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);

LinkedNewsChatApp/Views/NewsEdit/Create.cshtml
@model LinkedNewsChatApp.Data.News

@{
    ViewData["Title"] = "Додавання новин";
}
<head>
    
<link rel="stylesheet" href="~/css/NewsCrate syle.css" asp-append-version="true" />
</head>
<h1 id="Crt_main">Create</h1>

<h4>News</h4>
<hr />
<div id="create_news" class="row">
    <div id="Crt_frm" >
         @using (Html.BeginForm("Create", "NewsEdit", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div id="Crt_title" class="form-group">
                <label asp-for="title" class="control-label"></label>
                <input asp-for="title" class="form-control"  />
                <span asp-validation-for="title" class="text-danger"></span>

            </div>
            <div id="Crt_text" class="form-group">
                <label asp-for="text" class="control-label"></label>
                <textarea id="Crt_It" asp-for="text" class="form-control" ></textarea>
                <span asp-validation-for="text" class="text-danger"></span>
            </div>
            <div id="Crt_photo" class="form-group">
                <label asp-for="photo" class="control-label"></label>
                <input type="file" name="photo" class="form-control" required />
                <!--<span asp-validation-for="photo" class="text-danger"></span>-->
            </div>
                <!-- <div id="Crt_category" class="form-group">
                    <label asp-for="Category" class="control-label"></label>
                    <textarea id="Crt_It" asp-for="Category" class="form-control"></textarea>
                    <span asp-validation-for="Category" class="text-danger"></span>
                </div>
               -->
                <div class="form-group">
                    <label for="dropdownMenu">Category</label>
                    <select id="dropdownMenu" name="Category" class="form-control" required>
                        <option value="Загальне">Загальне</option>
                        <option value="Спорт">Спорт</option>
                        <option value="Політика">Політика</option>
                        <option value="Війна">Війна</option>
                        <option value="Наука">Наука</option>
                        <option value="Економіка">Економіка</option>
                        <option value="Технології">Технології</option>
                        <option value="Лайт">Лайт</option>
                        <option value="Погода">Погода</option>


                    </select>
                </div>

                <div id="Crt_pass" class="form-group">
                    <label name="AdminPassword" class="control-label"></label>
                    <input type="password" name="password" class="form-control" required />
                    <!--<span asp-validation-for="photo" class="text-danger"></span>-->
                </div>
            <!--<div class="form-group">
                <label asp-for="Time" class="control-label"></label>
                <input asp-for="Time" class="form-control" />
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>-->
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
        }
    </div>
</div>

<div>
     <a id="Na" asp-action="Index">Повернутись до списку новин</a>
     <br/>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LinkedNewsChatApp/Views/NewsEdit/DataView.cshtml
@model LinkedNewsChatApp.Data.News

@{
    ViewData["Title"] = "Опис новини";
}
<head>
    <link rel="stylesheet" href="~/css/data.css" asp-append-version="true" />
</head>

<h1 id="Nh1">ОПИС НОВИНИ</h1>

<div>
    <h4 id="Nh4">News</h4>
    <hr id="Nhr"/>
    <dl id="Ndl" class="row">

        <dd  class="Data_title">
            @Html.DisplayFor(model => model.title)
        </dd>

        <dd class="Data_text">
            @Html.DisplayFor(model => model.text)
        </dd>

        <dd class="Data_image">

            @{
                string base64String = Convert.ToBase64String(Model.photo);
            }
            <img src="data:image/png;base64, @(base64String)" width="930" />
        </dd>
        <dd id="Data_info" >

            @Html.DisplayFor(model => model.Time)
        </dd>
    </dl>
</div>
<div>

    <a id="Na" asp-action="Index">Повернутись до списку новин</a>
    <br />
</div>

LinkedNewsChatApp/Views/NewsEdit/Delete.cshtml
@model LinkedNewsChatApp.Data.News

@{
    ViewData["Title"] = "Видалення новини";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>News</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.photo)
        </dt>
        <dd class = "col-sm-10">
            @{/*Html.DisplayFor(model => model.photo)*/}
            @{

                string base64String = Convert.ToBase64String(Model.photo);
            }
            <img src="data:image/png;base64, @(base64String)" width="256" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Time)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Time)
        </dd>
    </dl>
     @using (Html.BeginForm("Delete", "NewsEdit", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <div class="form-group">
            <label name="AdminPassword" class="control-label"></label>
            <input type="password" name="password" class="form-control" required />
            <!--<span asp-validation-for="photo" class="text-danger"></span>-->
        </div>
        
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a id="Na" asp-action="Index">Повернутись до списку новин</a>
       <br/>
    </form>
    }
</div>

LinkedNewsChatApp/Views/NewsEdit/Edit.cshtml
@model LinkedNewsChatApp.Data.News

@{
    ViewData["Title"] = "Редагування новин";
}

<h1>Edit</h1>

<h4>News</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Edit", "NewsEdit", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="title" class="control-label"></label>
                    <input asp-for="title" class="form-control" />
                    <span asp-validation-for="title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="text" class="control-label"></label>
                    <input asp-for="text" class="form-control" />
                    <span asp-validation-for="text" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="photo" class="control-label"></label>
                    <input type="file" name="photo" class="form-control" />
                    <!--<span asp-validation-for="photo" class="text-danger"></span>-->
                </div>
                
                <!--
                <div class="form-group">
                    <label asp-for="Category" class="control-label"></label>
                    <input asp-for="Category" class="form-control" />
                    <span asp-validation-for="Category" class="text-danger"></span>
                </div>
                -->

                <div class="form-group">
                    <label for="dropdownMenu">Category</label>
                    <select id="dropdownMenu" name="Category" class="form-control" required>
                        <option value="Загальне">Загальне</option>
                        <option value="Спорт">Спорт</option>
                        <option value="Політика">Політика</option>
                        <option value="Війна">Війна</option>
                        <option value="Наука">Наука</option>
                        <option value="Економіка">Економіка</option>
                        <option value="Технології">Технології</option>
                        <option value="Лайт">Лайт</option>
                        <option value="Погода">Погода</option>
                    </select>
                </div>
                <div class="form-group">
                    <label name="AdminPassword" class="control-label"></label>
                    <input type="password" name="password" class="form-control" required />
                    <!--<span asp-validation-for="photo" class="text-danger"></span>-->
                </div>
                <!--<div class="form-group">
                    <label asp-for="Time" class="control-label"></label>
                    <input asp-for="Time" class="form-control" />
                    <span asp-validation-for="Time" class="text-danger"></span>
                </div>-->

                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        }
    </div>
</div>

<div>
    <a id="Na" asp-action="Index">Повернутись до списку новин</a>
   <br/>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LinkedNewsChatApp/Views/NewsEdit/Empty.cshtml
@model IEnumerable<LinkedNewsChatApp.Data.News>

@{
    ViewData["Title"] = "Новини";

}



<p>
    <a asp-action="Create" class="btn btn-primary">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-patch-plus" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M8 5.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V10a.5.5 0 0 1-1 0V8.5H6a.5.5 0 0 1 0-1h1.5V6a.5.5 0 0 1 .5-.5z" />
            <path d="m10.273 2.513-.921-.944.715-.698.622.637.89-.011a2.89 2.89 0 0 1 2.924 2.924l-.01.89.636.622a2.89 2.89 0 0 1 0 4.134l-.637.622.011.89a2.89 2.89 0 0 1-2.924 2.924l-.89-.01-.622.636a2.89 2.89 0 0 1-4.134 0l-.622-.637-.89.011a2.89 2.89 0 0 1-2.924-2.924l.01-.89-.636-.622a2.89 2.89 0 0 1 0-4.134l.637-.622-.011-.89a2.89 2.89 0 0 1 2.924-2.924l.89.01.622-.636a2.89 2.89 0 0 1 4.134 0l-.715.698a1.89 1.89 0 0 0-2.704 0l-.92.944-1.32-.016a1.89 1.89 0 0 0-1.911 1.912l.016 1.318-.944.921a1.89 1.89 0 0 0 0 2.704l.944.92-.016 1.32a1.89 1.89 0 0 0 1.912 1.911l1.318-.016.921.944a1.89 1.89 0 0 0 2.704 0l.92-.944 1.32.016a1.89 1.89 0 0 0 1.911-1.912l-.016-1.318.944-.921a1.89 1.89 0 0 0 0-2.704l-.944-.92.016-1.32a1.89 1.89 0 0 0-1.912-1.911l-1.318.016z" />
        </svg> Створити
    </a>
</p>

<main class="main columns">
   


</main>

LinkedNewsChatApp/Views/NewsEdit/Index.cshtml
@model IEnumerable<LinkedNewsChatApp.Data.News>

@{
    ViewData["Title"] = "Новини";
    
}



<p>
    <a asp-action="Create" class="btn btn-primary"> 
			<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-patch-plus" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M8 5.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V10a.5.5 0 0 1-1 0V8.5H6a.5.5 0 0 1 0-1h1.5V6a.5.5 0 0 1 .5-.5z"/>
  <path d="m10.273 2.513-.921-.944.715-.698.622.637.89-.011a2.89 2.89 0 0 1 2.924 2.924l-.01.89.636.622a2.89 2.89 0 0 1 0 4.134l-.637.622.011.89a2.89 2.89 0 0 1-2.924 2.924l-.89-.01-.622.636a2.89 2.89 0 0 1-4.134 0l-.622-.637-.89.011a2.89 2.89 0 0 1-2.924-2.924l.01-.89-.636-.622a2.89 2.89 0 0 1 0-4.134l.637-.622-.011-.89a2.89 2.89 0 0 1 2.924-2.924l.89.01.622-.636a2.89 2.89 0 0 1 4.134 0l-.715.698a1.89 1.89 0 0 0-2.704 0l-.92.944-1.32-.016a1.89 1.89 0 0 0-1.911 1.912l.016 1.318-.944.921a1.89 1.89 0 0 0 0 2.704l.944.92-.016 1.32a1.89 1.89 0 0 0 1.912 1.911l1.318-.016.921.944a1.89 1.89 0 0 0 2.704 0l.92-.944 1.32.016a1.89 1.89 0 0 0 1.911-1.912l-.016-1.318.944-.921a1.89 1.89 0 0 0 0-2.704l-.944-.92.016-1.32a1.89 1.89 0 0 0-1.912-1.911l-1.318.016z"/>
</svg> Створити</a>
</p>

   <main class="main columns">
@foreach (var item in Model)
{

  <section class="column_NI">
    <a class="article_NI"  asp-action="DataView" asp-route-id="@item.id"> 
      <figure class="article_image">
                    @{
                        string base64String = Convert.ToBase64String(item.photo);
                    }
                    <img src="data:image/png;base64, @(base64String)" width="180" />
      </figure></a>
      <div class="article_body">
        <h2 class="article_title">
                        @item.title
        </h2>
         <h2 class="article_title">
                        @item.Category
        </h2>
        <footer id="article_info" style="text-align:center; align-items:center;">
            <span style="margin-right: 1.5em;" id="actions" >
              <a asp-action="Edit" asp-route-id="@item.id"><i class="fas fa-edit"></i>
              </a> |
                <a asp-action="DataView" asp-route-id="@item.id"><i class="fas fa-info-circle"></i>
                </a> |
                <a asp-action="Delete" asp-route-id="@item.id"><i class="fas fa-trash"></i>
                 </a>
            </span>
             <br/>
            <div>
            <span id="time"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@item.Time</span>
              
            </div>
              
        </footer>
      </div>
   
  </section>
}


</main>
           
  
<div style="display: flex; justify-content: center;">
    <nav>
        <ul id="page_scroll" class="pagination">
            <li class="page-item @(ViewBag.CurrentPage == 1 ? "disabled" : "")">
                <a class="page-link" asp-action="Index"  asp-route-page="@(ViewBag.CurrentPage - 1)">&laquo;</a>
            </li>

            @if (ViewBag.TotalPages <= 5)
            {
                @for (int i = 1; i <= ViewBag.TotalPages; i++)
                {
                    <li class="page-item @(ViewBag.CurrentPage == i ? "active" : "")">
                        <a class="page-link" asp-action="Index"  asp-route-page="@i">@i</a>
                    </li>
                }
            }
            else
            {
                @if (ViewBag.CurrentPage > 3)
                {
                    <li class="page-item">
                        <a class="page-link" asp-action="Index"  asp-route-page="1">1</a>
                    </li>
                    @if (ViewBag.CurrentPage > 4)
                    {
                        <li class="page-item disabled">
                            <span class="page-link">...</span>
                        </li>
                    }
                }
                @for (int i = Math.Max(1, ViewBag.CurrentPage - 2); i <= Math.Min(ViewBag.TotalPages, ViewBag.CurrentPage + 2); i++)
                {
                    <li class="page-item @(ViewBag.CurrentPage == i ? "active" : "")">
                        <a class="page-link" asp-action="Index"  asp-route-page="@i">@i</a>
                    </li>
                }
                @if (ViewBag.CurrentPage < ViewBag.TotalPages - 2)
                {
                    @if (ViewBag.CurrentPage < ViewBag.TotalPages - 3)
                    {
                        <li class="page-item disabled">
                            <span class="page-link">...</span>
                        </li>
                    }
                    <li class="page-item">
                        <a class="page-link" asp-action="Index"  asp-route-page="@ViewBag.TotalPages">@ViewBag.TotalPages</a>
                    </li>
                }
            }

            <li class="page-item @(ViewBag.CurrentPage == ViewBag.TotalPages ? "disabled" : "")">
                <a class="page-link" asp-action="Index"  asp-route-page="@(ViewBag.CurrentPage + 1)">&raquo;</a>
            </li>
        </ul>
    </nav>
</div>