LinkedNewsChatApp/Controllers/ChatController.cs
using LinkedNewsChatApp.Models;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer;
using DataLayer;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;

namespace LinkedNewsChatApp.Controllers
{
    [Authorize]
    public class ChatController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMapper _mapper;
        private readonly ChatOperations _chatOperator;
        private readonly LinkedNewsRepository _repository;

        public ChatController(ILogger<HomeController> logger, IMapper map, ChatOperations chatOperator, LinkedNewsRepository repository)
        {
            _logger = logger;
            _mapper = map;
            _chatOperator = chatOperator;
            _repository = repository;
        }

        public IActionResult Index()
        {
            {
                return View();
            }
        }

        [HttpGet]
        public IActionResult Ban() 
        {
            return View();
        }
        [HttpPost]

        public IActionResult Ban(string Username, string Password, string dropdownMenu, string numericField)
        {
            if (Password == "d5n!_4RX")
            {
                if (dropdownMenu == "option1")
                {
                    int term = Convert.ToInt32(numericField);

                    _repository.Ban(Username, term); return View("Success");

                }
                else if (dropdownMenu == "option2")
                {
                    _repository.UnBan(Username);
                    return View("Success");
                }
                else
                {
                    return Content("Invalid option");
                }
            }
            else
            {
                return View("Incorrect");
            }

        }

        [HttpGet]
        public IActionResult DeleteMessage()
        {
            return View();
        }
        [HttpPost]
        public IActionResult DeleteMessage(string Username, string Password, string Message, string dropdownMenu)
        {
            if (Password == "d5n!_4RX")
            {
                if (dropdownMenu == "Одне повідомлення")
                {
                    
                    _repository.DeleteMessage(Username, Message);
                    return View("Success");

                }
                else if (dropdownMenu == "Усі повідомлення")
                {
                    _repository.DeleteMessages(Username, Message);
                    return View("Success");
                }
                else
                {
                    return Content("Invalid option");
                }
            }
            else
            {
                return View("Incorrect");
            }

        }
    }
}

LinkedNewsChatApp/Controllers/NewsController.cs
using DataLayer.Entities;
using LinkedNewsChatApp.Data;
using LinkedNewsChatApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using Telegram.Bot;
using Telegram.Bot.Args;
using Telegram.Bot.Exceptions;
using Telegram.Bot.Types;
using Telegram.Bot.Types.Enums;
using Telegram.Bot.Types.ReplyMarkups;


namespace LinkedNewsChatApp.Controllers
{
    public class NewsController : Controller
    {

       

        List<string> data = new List<string>();
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly ApplicationDbContext _context;

        public NewsController(IWebHostEnvironment hostingEnvironment, ApplicationDbContext context)
        {
            _hostingEnvironment = hostingEnvironment;
            _context = context;
        }

        public async Task<IActionResult> Index(string Category = "Новини", int page = 1)
        {
            int pageSize = 10;
            var news = _context.news.AsQueryable(); ;
            if (Category != "Новини")
            {
                news = _context.news.Where(m => m.Category == Category).AsQueryable();
            }
            else
            {
             
            }

            int totalNews = await news.CountAsync();
            int totalPages = (int)Math.Ceiling((decimal)totalNews / pageSize);


            if (page < 1)
            {
                page = 1;
            }
            else if (page > totalPages)
            {
                page = totalPages;
            }
            if (totalNews!=0)
            {
                var selectedNews = await news.Skip((page - 1) * pageSize)
                                             .Take(pageSize)
                                             .ToListAsync();
                ViewBag.TotalPages = totalPages;
                ViewBag.CurrentPage = page;
                ViewBag.Category = Category;
                ViewData["Title"] = Category;

                return View(selectedNews);
            }
            else
            {
                ViewData["Title"] = Category;
                return View("Empty");
            }

        }
        public async Task<IActionResult> Data(int? id)
        {
            if (id == null || _context.news == null)
            {
                return NotFound();
            }

            var news = await _context.news
                .FirstOrDefaultAsync(m => m.id == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

    }
    
}

LinkedNewsChatApp/Views/Shared/Incorrect.cshtml
<div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
  <h1 style="font-weight: bold; background: red; ">Неправильний пароль!</h1>
</div>

LinkedNewsChatApp/Views/Shared/Success.cshtml
<div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
  <h1 style="font-weight: bold; color: green;">Зміни успішно застосовано!</h1>
</div>

LinkedNewsChatApp/Views/Shared/UserProfile.cshtml
@model UserModel
@{
ViewData["Title"] = "Профіль";
var imageAv = Model.AvatarId;
}

<div id="P_container" >
    <div id="P_mb" class="Profile_row align-items-center">
        <div class="col-lg-6 mb-4 mb-lg-0 text-center">
            <img src="/avatars/@(imageAv).png" width="420" height="480"/>
        </div>
        <div  class="col-lg-6 px-xl-10">
            <div id="P_name"  >
           @Html.DisplayFor(model => model.Username)
            </div>
            <ul id="P_text" class="list-unstyled mb-5 text-black">
                <li class="mb-2 mb-xl-3 display-28"><span class="display-26 me-2 font-weight-500">Email:</span>@Html.DisplayFor(model => model.Email)</li>
                <li class="mb-2 mb-xl-3 display-28"><span class="display-26 me-2 font-weight-500">Регіон:</span>@Html.DisplayFor(model => model.Region)</li>
                <li class="mb-2 mb-xl-3 display-28"><span class="display-26 me-2 font-weight-500">Про себе:</span>@Html.DisplayFor(model => model.Biography)</li>
            </ul>
   </div>

</div>
      
         
               

LinkedNewsChatApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
      
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LinkedNews</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <!--icon add-->
    <link rel="apple-touch-icon" sizes="57x57" href="/icon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/icon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/icon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/icon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/icon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/icon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/icon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/icon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/icon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/icon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/icon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/icon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/icon/favicon-16x16.png">
    <link rel="manifest" href="/icon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/icon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

</head>
<body class="body_wrapper">
    <header>
        <nav id="header_imp" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LinkedNews</a>
                <button id="navbar-tog" class="navbar-toggler fas fa-grip-vertical" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item text-white">
                                <a class="nav-link text-white" asp-area="" asp-controller="Chat" asp-action="Index">Чат</a>
                            </li>
                            <li class="nav-item text-white">
                                <a class="nav-link text-white " asp-area="" asp-controller="News" asp-action="Index">Новини</a>
                            </li>
                            <li class="nav-item text-white">
                                <a id="nav_profile" class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Profile">Профіль</a>
                            </li>
                            <li class="nav-item text-white">
                                <a id="nav_profile" class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="About">Про нас</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item text-white">
                                <a class="nav-link text-white" asp-controller="Home" asp-action="Register">Реєстрація</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item user-greeting">
                                Привіт, @User.Identity.Name
                            </li>
                            <li class="nav-item">
                                <a id="btn_logd" class="btn btn-outline-secondary text-white " asp-controller="Home" asp-action="Logout">Вийти</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a id="btn_logi" class="btn btn-outline-secondary text-white tex-large" asp-controller="Home" asp-action="Index">Увійти</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="background"></div>
            @RenderBody()
            
        </main>
    </div>

    <footer class="main_footer">
        <div>
            <p class="mrg_foot" style="font-family:Verdana, Geneva, Tahoma, sans-serif" ; text-align: center;><b>Контакти:</b></p>
            <div class="contact_Us">
                <p>
                    <a href="mailto:linkednewsapp@gmail.com"><img src="~/Footer_icons/gmail_ico.png" alt="Mail"></a>
                    <a href="https://t.me/LinkedNewsApp"><img src="~/Footer_icons/telegram_icon.png" alt="Telegram"></a>
                </p>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>